<?php
/**
 * Created by PhpStorm.
 * User: yueping
 * Date: 19-2-20
 * Time: 下午4:11
 */

class Jeans extends Finery
{
    public function show() {
        echo "牛仔裤   ";
        parent::show(); // TODO: Change the autogenerated stub
    }
}
