<?php
/**
 * Created by PhpStorm.
 * User: yueping
 * Date: 19-2-20
 * Time: 下午4:12
 */

class Sneakers extends Finery
{
    public function show()
    {
        echo "球鞋  ";
        parent::show(); // TODO: Change the autogenerated stub
    }
}
