<?php
/**
 * Created by PhpStorm.
 * User: yueping
 * Date: 19-2-20
 * Time: 下午4:10
 */

class Sunglasses extends Finery
{
    public function show() {
        echo "太阳眼镜   ";
        parent::show(); // TODO: Change the autogenerated stub
    }
}
