<?php

/**
 * Created by PhpStorm.
 * User: yueping1302
 * Date: 19-2-20
 * Time: 下午4:05
 * email:yueping1302@emao.com
 */
class TShirt extends Finery
{
    public function show() {
        echo "T恤衫   ";
        parent::show(); // TODO: Change the autogenerated stub
    }
}
